# Generated by Django 4.2.6 on 2023-10-07 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('customer_id', models.IntegerField()),
                ('action', models.CharField(max_length=255)),
            ],
        ),
    ]
